version: 1.0.{build}
image: Visual Studio 2017
environment:
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib64-msvc-14.1
  CTEST_OUTPUT_ON_FAILURE: 1

cache:
  - %APPVEYOR_BUILD_FOLDER%\build\resources -> .appveyor.yml, resources/resources.cmake

build_script:
  - ps: .ci\setup_appveyor.ps1
