language: generic
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/usr/
    - build/resources

addons:
  apt:
    sources: &sources_base
      - ubuntu-toolchain-r-test
    packages: &packages_base
      - g++-6
      - libcln-dev
      - libgmp-dev
      - libgtest-dev
      - openjdk-7-jdk
      - time
      - uuid-dev

matrix:
  include:
    - stage: dependencies
      os: linux
      env: CC=gcc-5 CXX=g++-5
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: dependencies
      os: linux
      env: CC=gcc-7 CXX=g++-7
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-7]
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, lcov]
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, python3]
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: dependencies
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=tidy
      script: TASK=dependencies source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0]
          packages: [*packages_base, clang-5.0]
    - stage: build
      os: linux
      env: CC=clang-3.6 CXX=clang++-3.6
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.6]
          packages: [*packages_base, clang-3.6]
    - stage: build
      os: linux
      env: CC=clang-3.7 CXX=clang++-3.7
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.7]
          packages: [*packages_base, clang-3.7]
    - stage: build
      os: linux
      env: CC=clang-3.8 CXX=clang++-3.8
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.8]
          packages: [*packages_base, clang-3.8]
    - stage: build
      os: linux
      env: CC=clang-3.9 CXX=clang++-3.9
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-3.9]
          packages: [*packages_base, clang-3.9]
    - stage: build
      os: linux
      env: CC=clang-4.0 CXX=clang++-4.0
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-4.0]
          packages: [*packages_base, clang-4.0]
    - stage: build
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0]
          packages: [*packages_base, clang-5.0]
    - stage: build
      os: linux
      env: CC=gcc-5 CXX=g++-5
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: build
      os: linux
      env: CC=gcc-7 CXX=g++-7
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-7]
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, lcov]
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=doxygen
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, doxygen, texinfo, texlive]
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, python3]
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: build
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=tidy
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0]
          packages: [*packages_base, clang-5.0]
    - stage: build
      os: osx
      osx_image: xcode7.3
      script: source .ci/build.sh
    - stage: build
      os: osx
      osx_image: xcode8.2
      script: source .ci/build.sh
    - stage: build
      os: osx
      osx_image: xcode8.3
      script: source .ci/build.sh
  allow_failures:
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
    - stage: dependencies
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons
    - stage: dependencies
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=tidy
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons
    - stage: build
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=tidy

before_install:
  - cd .ci/ && source setup_travis.sh && cd ../

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#carl"
    template:
      - "Commit to %{repository_name}/%{branch} from %{author}"
      - "%{commit_message}"
      - "Build: %{message} %{duration} %{build_url}"
