language: generic
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/usr/
    - $HOME/.sonar/cache
    - build/resources

addons:
  apt:
    sources: &sources_base
      - ubuntu-toolchain-r-test
    packages: &packages_base
      - g++-6
      - libcln-dev
      - libgmp-dev
      - libgtest-dev
      - openjdk-7-jdk
      - time
      - uuid-dev

matrix:
  include:
    - stage: dependencies
      os: linux
      compiler: g++-5
      env: CC=gcc-5 CXX=g++-5
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - stage: dependencies
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: dependencies
      os: linux
      compiler: g++-7
      env: CC=gcc-7 CXX=g++-7
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-7]
    - stage: dependencies
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, lcov]
    - stage: dependencies
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=coverity
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: dependencies
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, python3]
    - stage: dependencies
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=addons
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: build
      os: linux
      compiler: clang++-3.6
      env: CC=clang-3.6 CXX=clang++-3.6
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.6]
          packages: [*packages_base, clang-3.6]
    - stage: build
      os: linux
      compiler: clang++-3.7
      env: CC=clang-3.7 CXX=clang++-3.7
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.7]
          packages: [*packages_base, clang-3.7]
    - stage: build
      os: linux
      compiler: clang++-3.8
      env: CC=clang-3.8 CXX=clang++-3.8
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.8]
          packages: [*packages_base, clang-3.8]
    - stage: build
      os: linux
      compiler: clang++-3.9
      env: CC=clang-3.9 CXX=clang++-3.9
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-3.9]
          packages: [*packages_base, clang-3.9]
    - stage: build
      os: linux
      compiler: clang++-4.0
      env: CC=clang-4.0 CXX=clang++-4.0
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-4.0]
          packages: [*packages_base, clang-4.0]
    - stage: build
      os: linux
      compiler: clang++-5.0
      env: CC=clang-5.0 CXX=clang++-5.0
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0]
          packages: [*packages_base, clang-5.0]
    - stage: build
      os: linux
      compiler: clang++-6.0
      env: CC=clang-6.0 CXX=clang++-6.0
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty]
          packages: [*packages_base, clang-6.0]
    - stage: build
      os: linux
      compiler: g++-5
      env: CC=gcc-5 CXX=g++-5
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - stage: build
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
    - stage: build
      os: linux
      compiler: g++-7
      env: CC=gcc-7 CXX=g++-7
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-7]
    - stage: build
      os: osx
      osx_image: xcode7.3
      script: source .ci/build.sh
    - stage: build
      os: osx
      osx_image: xcode8.2
      script: source .ci/build.sh
    - stage: build
      os: osx
      osx_image: xcode8.3
      script: source .ci/build.sh
    - stage: build
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=doxygen
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, doxygen, texinfo, texlive, texlive-latex-extra, latex-xcolor, ghostscript]
    - stage: build
      os: linux
      compiler: clang++-5.0
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=tidy
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0]
          packages: [*packages_base, clang-5.0]
    - stage: build
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, lcov]
    - stage: build
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=coverity
      script: cat cov-int/scm_log.txt
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base]
        coverity_scan:
          project:
            name: "smtrat/carl"
            description: "CArL"
          notification_email: "gereon.kremer@cs.rwth-aachen.de"
          build_command_prepend: "cov-configure --comptype gcc --compiler `which $CXX`"
          build_command: ".ci/build.sh MAKE_PARALLEL=-j1"
          branch_pattern: "master"
    - stage: build
      os: linux
      compiler: clang++-5.0
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=sonarcloud
      script: source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0, *sources_base]
          packages: [*packages_base, clang-5.0, *packages_base]
        sonarcloud:
          organization: "smtrat-github"
          token:
            secure: "nIGn6M7vkwD6HAKgS94QZIIU+A+dWOgqXzJ7lnAdGLXUx3cStVMO1LuOANttGyeGSJNj8Fa+YzwCx5EMQDvZW/b8cuoRld+I4gbmszUB6BXwQ6JJvpFczHrPpwyeo2LKrBN549aBCtOaLzw7rVPDzcdC6T39IvxpPXVCMTTjoq7Mp12HSWS8Ra8YIsOnJfYKVSxjCwcY9ICac70zpA6uKuWBNL13EBM+IpLACLFDKMcaIdb2CGyRvtbt7u8BOU9mjulRtpg1Ndc3eGEIIJJXM8lQTA+iMB6iapGWYbMB5Gwifrwy59UTgNbdR/6sWP5E5kxBGxn1lyp9VP6ChSS/b3Szhh0jUWaqBxoAK0Kh4KBeW7eeLvaUALuPmoNneGUZACrbNDq6aVzHUgwEKQTxF0reDkG3ZaEU+1NCukvLaI58OBxenb5bMOlEWzUMSMMuNO0MgVKXc3Nvr4oEm0USP6Ixky1AUTKTVDY87HHuQ+kCM/L5MQUQTwtQPuWF1zkDry+6A2LNABySla9AAtxlUth7rGvLwaTz2o3yMOIohQb12r8LqXnjESVcENk0f0gbyqeqM7aPcXAyqc6YDW9LBDSsWWa9SqxEfwz2zktzsWfKfCZWi4Fn7CaPdHGsGlSaGsXGovrT1DbyQPiTND0R1cinfrOqZBgwjWOB6JTol+g="
    - stage: build
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, python3]
    - stage: build
      os: linux
      compiler: g++-6
      env: CC=gcc-6 CXX=g++-6 TASK=addons
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
  allow_failures:
    - stage: build
      os: linux
      env: CC=clang-6.0 CXX=clang++-6.0
    - stage: build
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=tidy
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverity
    - stage: build
      os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 TASK=sonarcloud
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl
    - stage: build
      os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons

before_install:
  - cd .ci/ && source setup_travis.sh && cd ../

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#carl"
    template:
      - "Commit to %{repository_name}/%{branch} from %{author}"
      - "%{commit_message}"
      - "Build: %{message} %{duration} %{build_url}"
  slack:
    rooms:
      secure: "mL8Ku2omjsseTL5P2R2P3ddCedg8u9qSTKRjKNBhOYRJvpKNrIWr9fouP1tGsah9GBF+HL/JFWlA2sckCL9pURx6TdICHSgik1V/48QhpPKrV+ZkCmKenw3+hdXQY3YP36Xpj/SCCSMyRovA6kacWL3k0gRGJ++dxZYrYF7oVd8ltwxNC6+1o9HCmJnueCME5GBCKCgtOhYOr7izkjQ9wtFJvCmxHcI9EZxMQjWXmcHfItaWD1YFhR0/7AbsxJ9xtYZD0OMJrOgRBau671wV603a0EctIPcv0uKzjSsvB3yLndGOcMRsA8x/OPrFoOHbpLZ9d4O9gY3lvW5oueV+KTbbvHMSxJtvB9q3F0ZJSDHoG7cn1E2xb4gOHRdu4FhwqYy9abUM0DVUI/f7GaL+DMgzKeTduLB6h4GhtGR7fcWaBpCJYN1k8o33Vf/OPwaoPVCeiDRQIFqrqjDRcBc7ONe096WAf61albpMW6iCr5cBHy/j9XqEAGHu6sYftogWm/YVRqSF9+vnZy41cfQU+SYlFtWusUepqX1X/Kei+MCwESuddBnWj+oX8N8nreI8ql2IHG79IQVeEZZKMowxmo2IMsNnvkMyRTQsOmFY2u4NMRGga71QRCSbNvl01KxQ2ilyQ8Gu9Kjbs1QJ76jhOutChCzwOBAgc5aREdNCaV0="
